version: "3"
services:
  redis:
    image: redis:3.2-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - egg-redis:/data
    networks:
      - docker_inote
    ports:
      - "6379:6379"
volumes:
  egg-redis:
networks:
  docker_inote:
    driver: bridge
